"""
pack_uploader.py — อัปโหลด .glpack ขึ้น GitHub Releases + อัปเดต packs.json
Tag รูปแบบ: pack-{game_id}-{YYYYMMDD-HHMMSS}  (ไม่ใช่ v* → ไม่ทริก app build)
"""

import os
import json
import base64
import urllib.request
import urllib.error
from datetime import datetime

from PyQt6.QtCore import QThread, pyqtSignal

GITHUB_REPO = "markkyzii2304-web/gamelang-translator"
GITHUB_API  = "https://api.github.com"
TIMEOUT_S   = 30


def _req(url: str, headers: dict, method: str = "GET",
         data: bytes | None = None) -> dict:
    """Simple HTTP request wrapper — raises on non-2xx"""
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    with urllib.request.urlopen(req, timeout=TIMEOUT_S) as r:
        return json.loads(r.read().decode("utf-8"))


class PackUploader:
    """อัปโหลด .glpack ไปยัง GitHub Releases แล้วอัปเดต packs.json"""

    def __init__(self, token: str):
        self.hdrs = {
            "Authorization": f"token {token}",
            "Accept":        "application/vnd.github+json",
            "User-Agent":    "GameLang-Uploader/1.0",
        }

    # ── Public entry point ────────────────────────────────────────────────────
    def upload(self, glpack_path: str, game_name: str,
               string_count: int,
               progress=None) -> str:
        """
        1. สร้าง GitHub Release (tag: pack-{game_id}-{timestamp})
        2. อัปโหลด .glpack เป็น release asset
        3. อัปเดต packs.json ใน repo หลัก
        คืน download URL
        """
        log = progress or (lambda m: None)
        game_id   = game_name.lower().replace(" ", "_")
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        tag       = f"pack-{game_id}-{timestamp}"

        log(f"สร้าง GitHub Release ({tag})...")
        release   = self._create_release(tag, game_name)
        upload_url = release["upload_url"].split("{")[0]

        log("อัปโหลด .glpack...")
        asset_name   = f"{game_id}.glpack"
        download_url = self._upload_asset(upload_url, glpack_path, asset_name)

        log("อัปเดต packs.json...")
        size_bytes = os.path.getsize(glpack_path)
        self._update_manifest(game_id, game_name, download_url,
                               string_count, size_bytes)

        return download_url

    # ── Helpers ───────────────────────────────────────────────────────────────
    def _create_release(self, tag: str, game_name: str) -> dict:
        payload = json.dumps({
            "tag_name":   tag,
            "name":       f"Thai Pack — {game_name}",
            "body":       (f"Pre-translated Thai pack for **{game_name}**\n"
                           f"Generated by [GameLang Translator]"
                           f"(https://github.com/{GITHUB_REPO})"),
            "draft":      False,
            "prerelease": False,
        }).encode()
        return _req(
            f"{GITHUB_API}/repos/{GITHUB_REPO}/releases",
            headers={**self.hdrs, "Content-Type": "application/json"},
            method="POST", data=payload,
        )

    def _upload_asset(self, upload_url: str,
                       path: str, name: str) -> str:
        with open(path, "rb") as f:
            data = f.read()
        result = _req(
            f"{upload_url}?name={name}",
            headers={**self.hdrs, "Content-Type": "application/octet-stream"},
            method="POST", data=data,
        )
        return result["browser_download_url"]

    def _update_manifest(self, game_id: str, game_name: str,
                          download_url: str, string_count: int,
                          size_bytes: int):
        """GET → แก้ไข → PUT packs.json"""
        # GET current content + sha
        info = _req(
            f"{GITHUB_API}/repos/{GITHUB_REPO}/contents/packs.json",
            headers=self.hdrs,
        )
        current = json.loads(
            base64.b64decode(info["content"]).decode("utf-8"))
        sha = info["sha"]

        # อัปเดต entry ของ game นี้
        packs = [p for p in current.get("packs", [])
                 if p.get("game_id") != game_id]
        packs.append({
            "game_id":      game_id,
            "game_name":    game_name,
            "language":     "th",
            "source_lang":  "zh-Hans",
            "string_count": string_count,
            "size_bytes":   size_bytes,
            "download_url": download_url,
            "pack_version": datetime.now().strftime("%Y.%m.%d"),
            "description":  f"Thai translation for {game_name}",
        })
        current["packs"]   = packs
        current["updated"] = datetime.now().strftime("%Y-%m-%d")

        new_raw = json.dumps(current, ensure_ascii=False, indent=2)
        payload = json.dumps({
            "message": f"packs: update {game_id} Thai pack",
            "content": base64.b64encode(new_raw.encode()).decode(),
            "sha":     sha,
        }).encode()
        _req(
            f"{GITHUB_API}/repos/{GITHUB_REPO}/contents/packs.json",
            headers={**self.hdrs, "Content-Type": "application/json"},
            method="PUT", data=payload,
        )


# ── Worker ────────────────────────────────────────────────────────────────────
class PackUploadWorker(QThread):
    """อัปโหลด .glpack ใน background"""
    progress = pyqtSignal(str)
    finished = pyqtSignal(str)   # download URL หรือ "" ถ้าล้มเหลว

    def __init__(self, glpack_path: str, game_name: str,
                 string_count: int, github_token: str):
        super().__init__()
        self.glpack_path  = glpack_path
        self.game_name    = game_name
        self.string_count = string_count
        self.token        = github_token

    def run(self):
        try:
            uploader = PackUploader(self.token)
            url = uploader.upload(
                self.glpack_path, self.game_name,
                self.string_count,
                progress=lambda m: self.progress.emit(m),
            )
            self.progress.emit(f"✓ อัปโหลดสำเร็จ — pack พร้อมให้ผู้อื่นดาวน์โหลด")
            self.finished.emit(url)
        except Exception as e:
            self.progress.emit(f"⚠ อัปโหลดไม่สำเร็จ: {e}")
            self.finished.emit("")
